### ISSUE TITLE
When attempting to place gems in gem locks, the gem disappears

### ISSUE THREAD

**Issue by ZakFahey** [Pryaxis/TShock#2140] opened 2020-10-23 15:56 UTC
Logs: [2020-10-23_08-48-19.log](https://github.com/Pryaxis/TShock/files/5430507/2020-10-23_08-48-19.log)

TShock build number: 4.4.0.0 - pre-release 13

#### Reproduction steps (if applicable)?

1) Place a gem lock
2) Get a corresponding large gem and attempt to place it by right clicking on the lock
3) Notice that the gem isn't placed; it just disappears.

This was with no extra plugins, just stock TShock

**Comment by ZakFahey** [comment] 2020-10-23 23:02
I can confirm that it doesn't work with removing the gem either. When you try to do that, nothing happens when you right click, and the gem remains in the gem lock.

**Comment by ghost** [comment] 2020-11-09 14:09
Duplicate of #2036?

**Closed as completed** 2020-11-13 08:35 UTC
Labels: Confirmed
