### ISSUE TITLE
Town NPCs Disappear Randomly

### ISSUE THREAD

**Issue by Marcus101RR** [Pryaxis/TShock#1365] opened 2016-12-29 07:13 UTC
Build: https://travis.tshock.co/general-devel/1426/

This issue requires more investigation, numerous people have reported that the NPCs are randomly disappearing. One player has reported that "The Guide" comes around 4:30 AM, and disappears on 4:30 PM. I have not confirmed that specific issue yet.

However, I have noticed that NPCs just vanish without a slain message, and it seems that they didn't die from any noticeable hostilities. We attempted to see if the NPCs disappear when no player is nearby and the NPC is suppose to be teleported back to their house.

After butchering, and asking players to leave the vicinity of these Town NPCs, some disappeared on teleport. I believe it has something to do with them getting teleported to their houses, or perhaps general teleportation.

**Comment by tlworks** [comment] 2016-12-29 11:20
Can confirm this happens on the latest Travis release, now I do wonder whether this has to do either with the fact we would have to switch to a new world again, since this was the case with 1.3.3 (I believe?). NPC's would on kept disappearing until we moved to a new world.

**Comment by OnsenManju** [comment] 2017-01-06 10:33
I'm not sure this is the same issue as reported here, Terraria's developer said [it was fixed in 1.3.4.2](https://www.reddit.com/r/Terraria/comments/5db4pv/all_my_npcs_disappeared_after_entering_the_game/da3rf7z/), and in changelog.txt:
> Version 1.3.4.2 Changes------------------------------------
> 	Fixed town npcs potentially disappearing if you load a map using a non-english language

But I've also heard a similar issue at the Steam forum few days ago, so I wonder if this is the problem regarding TShock.

**Comment by ProfessorXZ** [comment] 2017-01-06 16:29
Reproduce this with the vanilla server.

**Comment by Marcus101RR** [comment] 2017-01-10 18:03
@ProfessorXZ I can confirm that this is not a Vanilla Issue, NPCs have not disappeared when leaving their vicinity.

**Comment by nicatronTg** [comment] 2017-01-10 20:23
After the move to Mintaka, this means that it likely has something to do with how we handle packets. At least we know it's not the API now.

**Comment by ProfessorXZ** [comment] 2017-04-19 10:59
Can't reproduce with TShock 4.3.23

**Comment by ProfessorXZ** [comment] 2017-07-06 11:05
Given the fact noone gave any input on this for 3 months (and that I couldn't reproduce it earlier) I don't see any reason for keeping this issue open. Feel free to reopen it if it actually happens.

**Closed by ProfessorXZ** 2017-07-06 11:05 UTC
