### ISSUE TITLE
Defender's Medal bug?

### ISSUE THREAD

**Issue by tanpro260196** [Pryaxis/TShock#1410] opened 2017-03-18 07:14 UTC
Some player on my server have informed me a way to have infinite Defender's Medal from the Tavernkeep.
The first time you talk to him (Tavernkeep) he will give you 5 medals.

On Single map, you will have to wait untill the next day to get another 5. But on my server, player only need to exit the server and join again to get another 5.

Not sure if this is a Terraria bug or tshock bug, but it only happen on the Server.

Using lastest tshock stable.

**Comment by ProfessorXZ** [comment] 2017-07-03 21:20
I wasn't able to reproduce this. @tanpro260196 please check if it's still an issue.

**Comment by Victorsueca** [comment] 2017-07-15 12:15
It is still an issue, happened to me just now, writing this with terraria open. Apparently logging out and then in to the server causes the guy to forget he just gave you 5 medals. Using the same character, connecting from the same IP and using the same server-side account login.

**Comment by ProfessorXZ** [comment] 2017-07-18 22:53
I tested it again and still can't reproduce the issue.

**Comment by Victorsueca** [comment] 2017-07-19 14:50
I made a video where I get to reproduce it
[https://youtu.be/0I-gw38bxoc](url)

**Comment by tanpro260196** [comment] 2017-07-19 22:32
As far as I know, it need to be a new character and server must use ssc.

**Comment by Victorsueca** [comment] 2017-07-20 14:15
Indeed, the server on the video is using SSC and the character I used has never been used in another server or singleplayer world.

**Comment by MarioE** [comment] 2017-07-24 20:08
This seems to be the case because the player file isn't saved in SSC, which means the flag that the character has talked to the bartender is never saved. So the character can keep getting the defender medals. There doesn't seem to be a great solution to this, besides asking the devs to send the flag to servers.

**Comment by Ijwu** [comment] 2017-07-25 14:08
Sounds like we know what may be causing this now and can only hope to make Re-Logic aware and discuss a possible solution.

**Comment by QuiCM** [comment] 2017-12-11 07:50
@hakusaro Do you know if Re-Logic are aware of this? Is this something we can request?

**Comment by hakusaro** [comment] 2017-12-11 07:54
@QuiCM requested sync, will report back later.

**Comment by hakusaro** [comment] 2017-12-11 08:24
Status is now `RL-MaybeAccepted`.

**Comment by bartico6** [comment] 2021-05-19 05:39
This issue is now partially fixed as of 1.4.

Non SSC servers are completely covered - there is a check in game code that makes sure you can't spawn it more than once per character.

SSC servers.... are not so lucky. The flag for whether or not you have talked to the tavernkeep is saved to the player file.... which is not saved if you're in SSC mode. So, fresh characters that never talked to the tavernkeep will continue to be able to infinitely spawn medals, while those who have already talked to him outside of SSC will not.

This appears to be intentional, too, so I think this issue can be closed now.

**Closed by bartico6** 2021-05-19 05:39 UTC
Labels: Blocked, Pending, RL-MaybeAccepted

**Comment by Shrizt** [comment] 2023-03-15 17:54
this is still issue in SSC TShock latest.
Is there other open topic or this need to be continued.
How to avoid players to cheat if SSC?

**Comment by drunderscore** [comment] 2023-03-15 18:19
@Shrizt You are unfortunately correct, this is still an issue for SSC, though noted above is that it seems intentional by Re-Logic... however I'd still be willing to transfer and re-open this on [Pryaxis/Terraria](https://github.com/Pryaxis/Terraria) where Terraria-specific issues live.

I'll think about it and likely move it in just a bit.
