### ISSUE TITLE
Can't disable automatic world saving

### ISSUE THREAD

**Issue by OnsenManju** [Pryaxis/TShock#1407] opened 2017-03-07 02:32 UTC
Both of the following don't work. Autosaving always performs at 4:30am in-game time.

- ` "AutoSave": false, ` in config.json
- [`autosave`](https://github.com/NyxStudios/TShock/blob/master/TShockAPI/TShock.cs#L1534) toggle command (available only on console)

Tested TShock 4.3.22 (Mintaka), 4.3.20 and 4.3.16.

**Comment by tlworks** [comment] 2017-03-07 15:59
This is most likely related to my previous issue and someone else's issue which included that _QUITE A LOT_ of config options do not work with OTAPI.

**Comment by OnsenManju** [comment] 2017-03-08 10:18
Hmm I don't think this issue is due to OTAPI, because the oldest version of Terraria which I have (1.3.1.1) also doesn't work. (So I tested on TShock 4.3.16 too)

But currently Terraria's class (like `Main.autoSave`) cannot be fiddled directly from TShock API, so if this is correctable, I guess OTAPI is the only way to do that, as you said.

**Comment by hakusaro** [comment] 2017-03-21 02:07
cc @DeathCradle re. modification needed

**Comment by DeathCradle** [comment] 2017-03-21 11:35
I believe it was caused by `Terraria.WorldGen.saveAndPlay()` being called without checking for `Terraria.Main.autoSave` in Terraria.
OTAPI 2.0.0.17 should now fix this.

**Comment by ProfessorXZ** [comment] 2017-07-03 21:26
No reports have been made in the past 2 months and the problem doesn't seem to occur anymore (tested 3 times). Closing.

**Closed by ProfessorXZ** 2017-07-03 21:26 UTC
Labels: Needs Investigation
