### ISSUE TITLE
Big Desync Issue Between Players and Server

### ISSUE THREAD

**Issue by SnakeASaur** [Pryaxis/TShock#1779] opened 2020-05-18 22:52 UTC
* TShock version: 1.4
* TShock build number (if known):

#### Reproduction steps (if applicable)?

Just normal playing, building interacting with doors and chests

Once it happens, everyone else is moving around as normal on your screen, but to them you are frozen in one spot until you die at which point any progress made during that time is lost.

#### Any stack traces or error messages (if known)?

```
PUT SUPER LONG ERROR MESSAGES IN THE TICK MARKS
```

#### Any screenshots?
![image0](https://user-images.githubusercontent.com/65572887/82266708-46422f80-991f-11ea-951d-b21bdb48a165.jpg)

Don't have access to server console, using hosting provider

#### Any log messages from files that end in `.log` or `.txt`?

 - TShock: INFO: SnakeASaur (73.15.24.252) from 'default' group joined. (1/8)
2020-05-18 15:07:49 - Utils: INFO: Broadcast: SnakeASaur has joined.
2020-05-18 15:07:59 - GetDataHandlers: INFO: You authenticated successfully as user You.
2020-05-18 15:08:00 - TShock: INFO: You (67.164.41.107) from 'default' group joined. (2/8)
2020-05-18 15:08:00 - Utils: INFO: Broadcast: You has joined.
2020-05-18 15:08:08 - Utils: INFO: Broadcast: You has left.
2020-05-18 15:08:08 - TShock: INFO: You disconnected.
2020-05-18 15:08:24 - GetDataHandlers: INFO: You authenticated successfully as user You.
2020-05-18 15:08:24 - TShock: INFO: You (67.164.41.107) from 'default' group joined. (2/8)
2020-05-18 15:08:24 - Utils: INFO: Broadcast: You has joined.
2020-05-18 15:11:43 - Utils: INFO: SnakeASaur tried to execute /group add'.
2020-05-18 15:17:46 - Utils: INFO: Broadcast: Saving world. Momentary lag might result from this.
2020-05-18 15:18:04 - Utils: INFO: Broadcast: SnakeASaur has left.
2020-05-18 15:18:04 - TShock: INFO: SnakeASaur disconnected.
2020-05-18 15:18:06 - GetDataHandlers: INFO: SnakeASaur authenticated successfully as user SnakeASaur.
2020-05-18 15:18:07 - TShock: INFO: SnakeASaur (73.15.24.252) from 'default' group joined. (2/8)
2020-05-18 15:18:07 - Utils: INFO: Broadcast: SnakeASaur has joined.
2020-05-18 15:25:54 - GetDataHandlers: INFO: Anamek authenticated successfully as user Anamek.
2020-05-18 15:25:55 - TShock: INFO: Anamek (174.126.56.177) from 'default' group joined. (3/8)
2020-05-18 15:25:55 - Utils: INFO: Broadcast: Anamek has joined.
2020-05-18 15:27:46 - Utils: INFO: Broadcast: Saving world. Momentary lag might result from this.
2020-05-18 15:34:57 - Utils: INFO: Broadcast: SnakeASaur has left.
2020-05-18 15:34:57 - TShock: INFO: SnakeASaur disconnected.
2020-05-18 15:35:00 - GetDataHandlers: INFO: SnakeASaur authenticated successfully as user SnakeASaur.
2020-05-18 15:35:01 - Utils: INFO: Broadcast: Anamek has left.
2020-05-18 15:35:01 - TShock: INFO: Anamek disconnected.
2020-05-18 15:35:01 - TShock: INFO: SnakeASaur (73.15.24.252) from 'default' group joined. (2/8)
2020-05-18 15:35:01 - Utils: INFO: Broadcast: SnakeASaur has joined.
2020-05-18 15:35:12 - GetDataHandlers: INFO: Anamek authenticated successfully as user Anamek.
2020-05-18 15:35:13 - TShock: INFO: Anamek (174.126.56.177) from 'default' group joined. (3/8)
2020-05-18 15:35:13 - Utils: INFO: Broadcast: Anamek has joined.
2020-05-18 15:37:46 - Utils: INFO: Broadcast: Saving world. Momentary lag might result from this.
2020-05-18 15:39:02 - Utils: INFO: Broadcast: SnakeASaur has left.
2020-05-18 15:39:02 - TShock: INFO: SnakeASaur disconnected.
2020-05-18 15:39:05 - GetDataHandlers: INFO: SnakeASaur authenticated successfully as user SnakeASaur.
2020-05-18 15:39:06 - TShock: INFO: SnakeASaur (73.15.24.252) from 'default' group joined. (3/8)
2020-05-18 15:39:06 - Utils: INFO: Broadcast: SnakeASaur has joined.
2020-05-18 15:47:46 - Utils: INFO: Broadcast: Saving world. Momentary lag might result from this.
#### What plugins and what versions of those plugins are you running?
none

**Comment by hakusaro** [comment] 2020-05-19 01:13
Can you upload a higher res screenshot?

**Comment by kubedzero** [comment] 2020-05-19 03:03
+1, not sure if I'm seeing the exact same issue but essentially I saw instances where, with two people in the server, one would appear frozen on my screen even though they were moving around, interacting, having AI follow them, etc. It seemed that I was the only thing that didn't see them live on screen.

This was with a dedicated computer running the pre-1 release and two computers on the same LAN connected to the server. 

I switched back to the default Terraria server and didn't see any of the same issues. 

Thanks and let me know if you need more details! I'll see if I can capture a screenshot of the network thing next time I have it running.

**Comment by hakusaro** [comment] 2020-05-19 07:35
As many clues as you can possibly provide would be nice. What items were people using? What were people doing? Boss fight? Old world? New world? etc

Can't really make an inference as to what the problem is without getting as much of a picture of your server as we can to try and test the problem

**Comment by hakusaro** [comment] 2020-05-19 09:17
I'm saving my notes here because I have to go to bed. I had @SnakeASaur can reliably reproduce the issue on their server. That server has these attributes:
1. Server has SSC on.
2. MOTD is all messed up up from some old version of TShock (has old colors, entire thing displays wrong, etc).
3. UUID login is on.
4. SSC database wiped after 1.4 migration.

When I connected, I observed that players were stationary. I also observed in net debug that packet 13 wasn't being sent to me corresponding with movement. I moved around a lot and confirmed that other players were getting my player update packets but I wasn't getting theirs. When this happens to them, a death "resyncs" them, i.e., the updates start being sent to all connected clients again before it breaks.

On my branch `h/verbosesync`, I added some debug for players disabled to make sure it wasn't Bouncer. I also removed the "reimplementation of Terraria sync" mystery code that we have in `GetDataHandlers`. When I connected to the server after @SnakeASaur installed this dev version, I observed him in the login process. I was able to see his character and brief movement before he was teleported to his remembered leave position. At the time he teleported, he became invisible. I confirmed no player updates were being sent.

**Comment by hakusaro** [comment] 2020-05-19 09:23
After he disabled `RememberLeavePos` (set it to false in `config.json`), he didn't become invisible but still didn't move or send player updates on my end.

**Comment by hakusaro** [comment] 2020-05-19 09:33
Narrowed it down to SSC. If SSC is on, pretty reliably happens. If it's off, it doesn't happen.

**Comment by hakusaro** [comment] 2020-05-19 09:41
Oh and `RememberedLeavePos` is a red herring. Works fine with SSC off.

**Comment by SnakeASaur** [comment] 2020-05-19 09:46
Was a pleasure testing with you. If anyone else wants to run testing, shoot me a DM on discord and I can change builds, etc.

**Comment by SnakeASaur** [comment] 2020-05-19 09:58
Update: Pre2 dll  is not yielding the same results, at least upon a join. Server is still:

-SSC Enabled
-RememberedLeavePos enabled

**Comment by SnakeASaur** [comment] 2020-05-19 10:47
@kubedzero Can you send me a discord DM, I may have a solution. @SnakeASaur#9813

**Comment by Ristellise** [comment] 2020-05-19 10:54
Debated over on discord with SnakeASaur, my best guess would be [MySQL 8 Commit](35198647a1944241ede866d5b61a7324decf29b7). Since it's related to groups et all.

**Comment by hakusaro** [comment] 2020-05-19 18:14
@Ristellise is the issue no longer happening on pre2? Because it makes very little sense. I sent @SnakeASaur a build that was based on pre2 changes that worked without SSC on. I can’t rule out that my changes didn’t independently screw something else up but I’d be quite surprised if the MySQL command changed anything.

**Comment by dly2424** [comment] 2020-05-20 00:29
Pre 2 definitely has this issue still, havent tried 3 just yet.
So unless there was work done on this, still present. Pretty major issue.

Seems to happen every death. Players desync and cant open chests and such. Seem to be moving around on their screen but are stuck at their spawn point invincible for others.

**Comment by hakusaro** [comment] 2020-05-20 01:12
@dly2424 thanks for your feedback on this

**Comment by QuiCM** [comment] 2020-05-20 03:47
From Discord: May also happen without SSC enabled. No supporting evidence provided

**Comment by kubedzero** [comment] 2020-05-20 03:51
> From Discord: May also happen without SSC enabled. No supporting evidence provided

+1, I don't use SSC and saw this happen on pre-1. I have yet to test with pre-3

**Comment by dly2424** [comment] 2020-05-20 11:31
> > From Discord: May also happen without SSC enabled. No supporting evidence provided
> 
> +1, I don't use SSC and saw this happen on pre-1. I have yet to test with pre-3

+1 as well, SCC isnt enabled here either.
Seemingly desyncing every death and its fixed with a relog until you die yet again.

**Comment by LeaHiHi** [comment] 2020-05-20 17:50
After doing some digging through tshock.sqlite this problem arises when the server tries to spawn the player anywhere other then world spawn, i.e. when either spawnX or spawnY for tsCharacter in the databse, ssc on, is anything other then -1. So this is caused by setting your spawn somewhere else, so beds cause this issue as far as i can tell. This might help you replicate it.

**Comment by hakusaro** [comment] 2020-05-20 17:53
This should be solved in the latest experimental build. I’m working right now so I can’t do much other than day that it should be fixed. If you’re capable you can try that build and test.

I’m currently planning on a release when I’m on my lunch break so you can wait a couple hours until then.

Lucas Nicodemus
http://keybase.io/xn

**Comment by hakusaro** [comment] 2020-05-20 18:00
This is the precise build where it should be ok: https://github.com/Pryaxis/TShock/actions/runs/110645397

**Comment by hakusaro** [comment] 2020-05-23 03:07
This is assumed to be fixed. If the issue is still happening, let us know.

**Closed as completed by hakusaro** 2020-05-23 03:07 UTC
Labels: followup-required, Confirmed

**Comment by syeare** [comment] 2021-02-14 20:26
Um, actually I'm having this issue as well. Should I make a New Issue?

Info about the server:
• vanilla/no plug-in TShock server,  v4.4.0-pre15
• Terraria version is GOG 1.4.1.2
• SSC enabled
• New world (created with TShock)

One of the players wasn't moving on anybody's screen, but he sent a video where he WAS moving and even broke some trees (which just broke and didn't drop anything). Of course, those trees didn't show as broken to everybody else. The data isn't old, we made a new world and everything, and there is no MOTD issue.

**Comment by Kojirremer** [comment] 2021-02-14 20:58
> 
> 
> Um, actually I'm having this issue as well. Should I make a New Issue?
> 
> Info about the server:
> • vanilla/no plug-in TShock server, v4.4.0-pre15
> • Terraria version is GOG 1.4.1.2
> • SSC enabled
> • New world (created with TShock)
> 
> One of the players wasn't moving on anybody's screen, but he sent a video where he WAS moving and even broke some trees (which just broke and didn't drop anything). Of course, those trees didn't show as broken to everybody else. The data isn't old, we made a new world and everything, and there is no MOTD issue.

Oh yeah, I've received lots of reports of this. I assumed it was due to problems in their ISP, but guess it was this, eh? It gets fixed when they get killed via the kill command.

**Comment by syeare** [comment] 2021-02-15 15:14
q

> 
> 
> > Um, actually I'm having this issue as well. Should I make a New Issue?
> > Info about the server:
> > • vanilla/no plug-in TShock server, v4.4.0-pre15
> > • Terraria version is GOG 1.4.1.2
> > • SSC enabled
> > • New world (created with TShock)
> > One of the players wasn't moving on anybody's screen, but he sent a video where he WAS moving and even broke some trees (which just broke and didn't drop anything). Of course, those trees didn't show as broken to everybody else. The data isn't old, we made a new world and everything, and there is no MOTD issue.
> 
> Oh yeah, I've received lots of reports of this. I assumed it was due to problems in their ISP, but guess it was this, eh? It gets fixed when they get killed via the kill command.

He made a lava pit next to the spawn so it looks like it starts working again so long as he dies in any way

**Comment by csmir** [comment] 2021-02-15 23:30
Desyncs are very common now, keeps frequently happening from a lot of sources, either being unable to hammer/break blocks, unable to see players move, not being able to place rope, actuation cant be seen by other players etc etc

**Comment by syeare** [comment] 2021-02-16 20:40
> 
> 
> Desyncs are very common now, keeps frequently happening from a lot of sources, either being unable to hammer/break blocks, unable to see players move, not being able to place rope, actuation cant be seen by other players etc etc

Is there a way to figure out what exactly is causing the issue?

**Comment by syeare** [comment] 2021-02-16 20:49
![image](https://user-images.githubusercontent.com/11952166/108119947-24203e00-7066-11eb-9893-d5d48f03b436.png)
The player named FarCry is the one with the desync issue, does this have anything to do with it? Same one who built the lava pit
