### ISSUE TITLE
Group deletion causes no access to the server

### ISSUE THREAD

**Issue by KibitzBlueFish** [Pryaxis/TShock#2165] opened 2020-11-22 19:31 UTC
Tshock docs don't talk about this, but if you delete guest group, new people won't be able to join the server except for those who are already signed in with an account created with /register and then /login. Please make people able to reset the access to their server

**Comment by csmir** [comment] 2020-11-22 19:34
While it is easily fixed in console or by a user with a full permission, this indeed is an issue that has also happened to me in the past.

**Comment by KibitzBlueFish** [comment] 2020-11-22 19:35
I fixed this by re-creating the guest group and giving it some perms, yet there is another issue in this: refreshing permissions and groups with /reload doesn't work with the access to the server for the guest group and you are forced to reboot the server

**Comment by KibitzBlueFish** [comment] 2020-11-22 19:37
Also, i don't see any permissions that speaks about server joining, so the server probably takes reference to the group's name "guest" instead of its permissions. Developers should make tshock such that super admins can reset all groups

**Comment by moisterrific** [comment] 2021-05-12 05:00
Personally I've not encountered this problem, but that sounds annoying if you've deleted it accidentally. The TShock Docs should be updated to warn users against doing this. 

Since there's no "undo" feature built into TShock, would it be a good idea to add an extra layer of confirmation warning when a user is trying to delete the guest group?

**Comment by bartico6** [comment] 2021-05-12 05:01
Technically speaking one could just... create a new group called guest?

But that is besides the point, if it can be confirmed that deleting `guest` causes the server to be inaccessible, I will personally update the docs to warn against that.

If you'd be so kind @moisterrific :-)

**Comment by moisterrific** [comment] 2021-05-12 14:02
> Technically speaking one could just... create a new group called guest?
> 
> But that is besides the point, if it can be confirmed that deleting `guest` causes the server to be inaccessible, I will personally update the docs to warn against that.
> 
> If you'd be so kind @moisterrific :-)

Just tested it, deleting guest group made absolutely no difference. An unregistered player can still join the server without issue.

This issue should be closed since the problem was fixed.

![image](https://user-images.githubusercontent.com/57187883/117987945-ef402200-b308-11eb-879d-4bde48a52f51.png)

**Comment by moisterrific** [comment] 2021-05-12 14:12
Actually, ignore the above post. I did not restart the server after deleting guest, the issue happened after restart.

Upon restarting I got this error msg in the map select screen.
![image](https://user-images.githubusercontent.com/57187883/117989227-23681280-b30a-11eb-9497-5dc618b931fe.png)

Next, trying to connect with an unregistered user put me in a perpetual requesting tile data screen. 
![Terraria_2021_05_12_10_07_15_247](https://user-images.githubusercontent.com/57187883/117989308-32e75b80-b30a-11eb-9977-529ea2769f10.png)

Finally, this is what shows up in console when the unregistered user attempts to join.
![image](https://user-images.githubusercontent.com/57187883/117989610-7641ca00-b30a-11eb-90d2-0699f9d1e3fd.png)

Just to rule out anything else I tried joining with a pre-registered user and it worked as usual. 

So yeah. @bartico6

**Comment by Quinci135** [comment] 2021-05-19 08:35
Similar discussion: https://github.com/Pryaxis/TShock/discussions/2083
Approximate reproduction:
1. Have configs set for `DefaultRegistrationGroupName` and/or `DefaultGuestGroupName` to a group that is non-existent (via group deletion or changing values)
2. Attempt joining/registration
3. Experience errors due to inability to get a group for the user

Maybe
* Tell people not to do this
* Check if these groups exist when config is loaded and stop server from loading along with a error warning (think this would be best)
* Auto-gen/select groups to be default & guest and set warning in console (could run into issues of someone having unintentional permissions)

**Comment by bartico6** [comment] 2021-05-19 14:49
> Tell people not to do this
> Check if groups exist and fail if they don't

Agree, should do both

> Auto-gen/select groups to be default & guest [...]

Dangerous, wouldn't do this

**Closed as completed** 2021-06-13 08:16 UTC
