### ISSUE TITLE
Player connecting issues

### ISSUE THREAD

**Issue by Puremin0rez** [Pryaxis/TShock#947] opened 2015-07-06 05:27 UTC
After a random amount of time, players are no longer able to join and get stuck on connecting or "Found Server.". Everyone playing can still play until they disconnect.

Running PR2 on Mono 4.0.2

**Comment by Efreak** [comment] 2015-07-06 23:45
I'm having this same issue. 

I'm also having another issue: I can't actually type into the server console once it starts listening. *ctrl+c* doesn't do anything; the only thing I've tried that has any effect is *ctrl+z*, and that just suspends the process until I `fg` or `bg` it.
- This might be related to my environment, I'm not sure. I'm running under byobu/tmux on linux and using zsh instead of bash.
- I had this issue with [TShock 4.3.0 GM (Prerelease) for Terraria 1.2.4.1](https://tshock.co/xf/index.php?threads/tshock-4-3-0-gm-prerelease-for-terraria-1-2-4-1.3759/) as well. I did not have it with previous versions.

I've tried the following setups as described here:

1. Mono 3.2.8+dfsg-4ubuntu4 with PR2:

    ````bash
    sudo apt-get install mono-complete
    mkdir -p ~/ts/tshock && cd ~/ts/tshock
    wget ...tshock.4.3.0-pre2.zip
    unzip tshock.4.3.0-pre2.zip
    rm ServerPlugins/Mysql.Web.dll
    mono-boehm TerrariaServer.exe
    ````
    I need to use mono-boehm (I think this means a different garbage collector, not sure) for it to work. I also need to remove ServerPlugins/Mysql.Web.dll. The server will now start. When I connect, however, the server log shows the connection, then Terraria gets stuck on *Found Server*.
2. Compile mono myself, then use the previous install

    ````bash
    sudo apt-get remove --purge mono-runtime mono-complete .....
    cd ~/ts
    git clone git@github.com:mono/mono.git && cd mono ./autogen.sh && make get-monolite-latest && ./configure && colormake -j4 && sudo make install && cd .. #compile/install mono, then go back
    cd ~/ts/tshock
    mono TerrariaServer.exe
    ````
    This has the same issue with having to remove the MySQL dll, and with connecting to the server; the only noticeable difference is that I can use mono and not mono-boehm.

3. Compile TShock myself, and try using it with the mono I compiled earlier.

    ````bash
    cd ~/ts
    git clone git@github.com:NyxStudios/Tshock.git tshock-git
    cd tshock-git
    xbuild /p:Configuration=Release TShock.sln
    #cp files so they're in the same folder structure as the release
    mono TerrariaServer.exe
    ````
    This works *exactly* the same as attempt 2. There are no noticeable differences at all.
4. Compile a debug build of TShock myself, and try using it with the mono I compiled earlier.

    ````bash
    cd ~/ts
    git clone git@github.com:NyxStudios/Tshock.git tshock-git
    cd tshock-git
    xbuild /p:Configuration=Debug TShock.sln
    #cp files so they're in the same folder structure as the release
    mono TerrariaServer.exe
    ````
    This works *exactly* the same as attempts 2 and 3. There are no noticeable differences at all.
    I had hoped that the debug build would include some kind of debugging output that I can give you, but it doesn't tell me anything. The output is the same as before.

**Comment by recon88** [comment] 2015-07-08 20:02
Same here. Players are not able to connect at all and stuck at "Found Server".  
Ports are opened and the Firewall isn't blocking it.

Running Debian Jessie with Mono 4.3.0.

**Comment by benv666** [comment] 2015-07-11 13:32
Same here with TShock v1.3.0.4 running on a self compiled mono 4.0.1 on Slackware64.
After removing ServerPlugins/TShockAPI.dll it works, although now half the server commands are missing (no big surprise).

**Comment by recon88** [comment] 2015-07-14 09:25
Seems to be fixed.

**Comment by recon88** [comment] 2015-07-20 13:07
So is this actually fixed or not?

**Comment by WhiteXZ** [comment] 2015-07-20 13:16
Haven't received any reports in 9 days, assuming so. If you're experiencing issues still, please try to reproduce them on build 497

**Comment by Efreak** [comment] 2015-07-24 00:19
I *was* still having the issue. Oddly, it's now working fine after I wiped everything so I could record it with ttyrec. I'm not sure what's going on there. Also, I'm not sure what 'build 497' is, since the releases don't seem to have build numbers on them?

**Comment by lincoln-b** [comment] 2017-07-01 20:30
I am now having the same issue in 2017. I suspect it may be because my vps has relatively little memory (2GB) but unsure. Mine either freezes on "Server Started" (after world load) or on the screen just after that, and when you try to connect, occasionally it will say "<ip address> is connecting...", but freeze on "Found Server" in the client. Did you ever resolve the issue?

**Comment by hakusaro** [comment] 2017-07-01 20:49
What's the output of free -m @lincoln-b?

**Comment by hakusaro** [comment] 2017-07-01 20:52
![img_1281](https://user-images.githubusercontent.com/532647/27765387-d4c0c9d8-5e6c-11e7-8696-63edd5435c5d.JPG)

**Comment by lincoln-b** [comment] 2017-07-01 22:09
The output of free -m is:

![image](https://user-images.githubusercontent.com/4949920/27765742-6855f402-5e77-11e7-8b74-e692f30e3264.png)

I saw that page but hoped it not be a problem because of https://www.vultr.com/docs/running-a-tshock-terraria-server

![image](https://user-images.githubusercontent.com/4949920/27765746-8aec879c-5e77-11e7-8aaf-79b06494a1fb.png)

**Comment by hakusaro** [comment] 2017-07-01 23:42
Can you clarify: is that free with or without Terraria running?

**Comment by lincoln-b** [comment] 2017-07-02 19:05
That's without. Running top with TerrariaServer running shows 99% CPU usage and ~5% memory usage.

**Comment by hakusaro** [comment] 2017-07-02 20:16
Can you run free -m with it running?

**Comment by lincoln-b** [comment] 2017-07-03 02:50
Yes. Here's free -m after it loads the world data and freezes:

![image](https://user-images.githubusercontent.com/4949920/27776446-e3fc4836-5f67-11e7-9b36-6716708d8f8c.png)

And here's top running as I start the server. CPU usage shoots up to 97-98%, and then falls after TerrariaServer freezes:

![image](https://im2.ezgif.com/tmp/ezgif-2-f04e9bdc98.gif)

**Comment by hakusaro** [comment] 2017-07-03 02:52
Neither of those are free -m...

**Comment by lincoln-b** [comment] 2017-07-03 02:52
Sorry, wrong screenshot. One sec.

**Comment by hakusaro** [comment] 2017-07-03 04:07
I would suggest adding a swap partition or file of standard size and see if those issues persist. Also, what version of mono are you using?

**Comment by hakusaro** [comment] 2017-07-03 04:08
Also, if you edit comments they aren't reflected in discord, so there's a high probability people assumed you never changed anything (like I did).

![screen shot 2017-07-02 at 10 07 48 pm](https://user-images.githubusercontent.com/532647/27777757-e76e85dc-5f72-11e7-9f73-96e9a74de15d.png)

**Comment by tylerjwatson** [comment] 2017-07-03 07:49
@lincoln-b Can you please post the output of `mono --version`.

Looks like it's still happening.  Reopening.

**Comment by lincoln-b** [comment] 2017-07-03 15:27
@hakusaro Thanks! I will look into making a swap partition. What do you mean by file of standard size?

@tylerjwatson Here it is:

![image](https://user-images.githubusercontent.com/4949920/27799291-dddee78c-5fd1-11e7-87cf-be36441fce6d.png)

**Comment by rautamiekka** [comment] 2017-07-03 16:29
^ Whether you're making a swap partition or a file you'll still have to worry about how much space you're giving it, and I read Ubuntu, for instance, stopped offering swap partitions in favor of files for performance and maintenance reasons.

**Comment by tylerjwatson** [comment] 2017-07-03 22:30
You have an ancient version of mono. Install mono >=5.0 or run tshock with the MONO_THREADS_PER_CPU environment variable.

`MONO_THREADS_PER_CPU=50 mono TerrariaServer.exe` 

And see if that fixes the issue.

**Comment by lincoln-b** [comment] 2017-07-03 22:48
Exporting MONO_THREADS_PER_CPU to 50 resolved the issue. Thank you!

I don't know why my version of mono is so out of date. I typed `sudo apt-get mono-complete` and that's what I got.

**Comment by hakusaro** [comment] 2017-07-03 22:49
We really need to bold and italicize this somewhere. I'm kicking myself for not asking if you did this first.

![screen shot 2017-07-03 at 4 48 58 pm](https://user-images.githubusercontent.com/532647/27809744-9756aaaa-600f-11e7-83fa-95619e81583a.png)

**Comment by lincoln-b** [comment] 2017-07-03 22:57
And I'm kicking myself for it being such an easy fix. Thanks for bearing with me.

**Comment by tylerjwatson** [comment] 2017-07-03 22:59
Ubuntu LTS has really old versions of packages. Consider adding the xamarin ppa for more recent mono releases.

Glad it fixes the issue, I am re-closing this again.

**Closed by tylerjwatson** 2017-07-03 22:59 UTC
Labels: Confirmed Issue, Mono
