### ISSUE TITLE
/help triggers OnChat hook

### ISSUE THREAD

**Issue by Fraxo** [Pryaxis/TShock#2111] opened 2020-08-09 02:27 UTC
* TShock version: 4.4.0 Pre12
* TShock build number (if known):

#### Reproduction steps (if applicable)?

1. Setup Terracord appropriately
2. Type /help
3. Check Discord relay
4. Leads to the screenshots below. 
/help in game triggers the OnChat hook and sends an empty message. If any arguments trail the command, they also get sent as a chat message.

#### Any screenshots?
[https://i.imgur.com/ESj2459.png](url)
[https://i.imgur.com/MMXXFDd.png](url)

#### What plugins and what versions of those plugins are you running?
Solely using Terracord and it's dependencies. Plugin ver 1.2.0.
Verified with Terracord dev to be an issue with TShock.

**Comment by hakusaro** [comment] 2020-08-10 03:53
This is probably something you'd get better help from if you were to ask TerraCord developers.

**Comment by bartico6** [comment] 2020-08-10 03:58
> 
> This is probably something you'd get better help from if you were to ask TerraCord developers.

```Verified with Terracord dev to be an issue with TShock.```

The issue is most likely with how special chat packets are handled by tshock (raising **chat events** for commands), not terracord itself.

**Comment by hakusaro** [comment] 2020-08-10 04:20
> Verified with Terracord dev to be an issue with TShock.

Would the Terracord dev please stand up

**Comment by bartico6** [comment] 2020-08-10 04:47
Terracord's dev is, I think, @ldilley 

The issue is actually with Terracord after inspecting both sources - Terracord hooks the TSAPI OnChat event which can & will contain commands. This means that the command format relogic made with command ids instead of /command will be sent as an empty message. (the chat id will be "Help" and the message will be empty for /help)
In fact the same issue will happen with ingame emotes - using /eol or just clicking the emote in your emote menu *should* cause an empty message as well.

As for the fix:  
It should instead hook PlayerHooks.OnChat from tshock which happens after all the chat handling has occured.
As a side note, it'd also make handling muted players *and* filtering commands dealt with by tshock, reducing the size and complexity of code seen in [their chat handler](https://github.com/FragLand/terracord/blob/master/Terracord/Terracord.cs#L165)

feel free to forward this @Fraxo unless the ping somehow works and the developer gets notified of my atting him.

**Comment by ldilley** [comment] 2020-08-10 11:17
Thank you much for the background information, @bartico6. This is quite helpful. I'll update the relevant portions of Terracord.

**Comment by QuiCM** [comment] 2020-09-10 04:51
Resolved in 3rd party plugin :) 
Thanks all

**Closed as completed by QuiCM** 2020-09-10 04:51 UTC
