### ISSUE TITLE
Rope Coils unable to be placed when only one is in the selected stack

### ISSUE THREAD

**Issue by AviKav** [Pryaxis/TShock#1670] opened 2019-04-06 07:03 UTC
* TShock version: 4.3.26

#### Reproduction steps

Select stack with exactly one (Silk/Vine/Web) Rope Coil.
Throw rope coil at vertical column of blocks

Expected:
- (Silk/Vine/Web) Rope Coil entity is thrown.
- (Silk/Vine/Web) Rope Coil is placed upon collision with solid blocks.
- Excess (Silk/Vine/Web) Rope is returned as dropped items.

Reality:
- (Silk/Vine/Web) Rope Coil entity is thrown.
- (Silk/Vine/Web) Rope Coil entity disappears upon collision with solid blocks.
- What would have been excess (Silk/Vine/Web) Rope had the coil been placed is returned as dropped items.

#### Notes
- `/group addperm <group> tshock.ignore.*` does not appear to change this.

**Comment by AviKav** [comment] 2019-04-06 07:50
Rope coils previously did not work as a result of anti-cheat which as reported in #1352, fixed in #1355, and moved in https://github.com/Pryaxis/TShock/commit/a4d9f0295a0858459c6ea6e5aab32ca3a7812d46#diff-3086bd09c54e93b5f9a34786586f710cR229.
The current anti-cheat exception checks to see if the tile being placed matches the item selected at the time the tile is being placed instead of at the time the projectile is thrown

**Comment by hakusaro** [comment] 2019-04-06 16:36
The only difference in logic between the two compared code paths (as expressed in #1355 and in a4d9f0295a0858459c6ea6e5aab32ca3a7812d46) is that we set `args.Handled = true;` instead of returning true because it's an event hook. The rest of the code paths are identical.

Can you help me reach the same conclusion you've come to? I'm having trouble identifying how the move could have changed the behavior here.

**Comment by AviKav** [comment] 2019-04-06 16:41
Sorry, I simply intended to document the history of the current anti-cheat exception (probably over-zealously). I didn't mean to imply that the move altered behavior

**Comment by hakusaro** [comment] 2019-04-06 16:42
Ahhh okay. So you're saying it was reported as fixed in #1355 -- not that you confirmed that it regressed? Just want to be on the same page here.

**Comment by AviKav** [comment] 2019-04-06 16:49
Yes, it did not regress.

**Comment by AviKav** [comment] 2019-04-06 16:54
Restating, #1355 checks the selected item at the time that the rope coil collides rather than the time that the rope coil is thrown. This means that if a coil is thrown then another item is selected or the last coil is consumed before, the rope coil is not placed.

Selecting another stack intermediately afterwards only occurred to me recently.

**Comment by QuiCM** [comment] 2019-04-12 00:33
Thanks. We can probably add checking for stacks of size 1 - swapping immediately after may be harder to capture.

**Comment by hakusaro** [comment] 2019-06-05 13:22
@all-contributors please add @AviKav for bug reports

_This is a test of a new feature hooray_

**Closed as completed** 2020-06-01 09:21 UTC
Labels: Low, Contribution Wanted
