### ISSUE TITLE
Fishing out Bloodmoon mini bosses is broken

### ISSUE THREAD

**Issue by moisterrific** [Pryaxis/TShock#1985] opened 2020-06-04 00:55 UTC
* TShock version: 4.4.0 pre-10

#### Reproduction steps (if applicable)?

1. Set worldevent to bloodmoon
2. Try to fish out a mini boss (ideally using Golden Rod w/ Master bait and sonar and fishing buffs)
3. See mini boss or any blood moon fishing mob name indicated by sonar potion
4. Reel in
5. Mini boss(es) do not spawn

#### Any screenshots?
Can post a gif if required.

#### Any log messages from files that end in `.log` or `.txt`? What are the last 100 log messages from the server console?
None

#### What plugins and what versions of those plugins are you running?
None, only TShockAPI

**Comment by moisterrific** [comment] 2020-06-04 00:57
All the mobs you can fish from Bloodmoon fail to spawn

Duke Fishron works fine though

For reference I tested using an owner account and a guest account. Neither were able to spawn blood moon NPCs. 

Duke Fishron could not be spawned by guest (no summon boss perm) so that's working as intended.

**Comment by Patrikkk** [comment] 2020-06-04 02:38
The OnFishNPC hook in Bouncer does send debug message if a packet is handled. Do you find any messages in your logs starting with "Bouncer / OnFishOutNPC rejected"?
So you're saying all mobs dont work, only Duke.

**Comment by moisterrific** [comment] 2020-06-04 02:46
Duke is working as intended, just that every other mob you can fish up won't spawn.

There were no debug messages in logs because I forgot to enable DebugLogs lol

**Comment by moisterrific** [comment] 2020-06-04 02:49
Alright enabled it and it says this:

`2020-06-03 22:48:50 - TextLog: VERBOSE: Bouncer / OnFishOutNPC rejected range checks from moisterrific`

I was fishing on a flying mount about a dozen tiles above the ocean if that makes any difference...

**Comment by Patrikkk** [comment] 2020-06-04 10:24
Thank you for the test! It was helpful. The issue is patched in the upcoming commit.

**Comment by moisterrific** [comment] 2020-06-04 13:12
Great, I’ll leave this open until the next pre-release, so we won’t have duplicate issues.

**Comment by hakusaro** [comment] 2020-06-05 03:46
> Great, I’ll leave this open until the next pre-release, so we won’t have duplicate issues.

I'm going to close it -- if it's broken we can re-open and we can have other issues closed. Most people don't check for dupes anyway :(

**Closed as completed by hakusaro** 2020-06-05 03:46 UTC

**Comment by JMCY26** [comment] 2020-06-05 18:01
This is present still in V11

**Comment by Patrikkk** [comment] 2020-06-05 18:02
Can you please describe what actions you are getting? 
Is `  "DebugLogs": `enabled in your config? Are you getting any messages related to `OnFishOutNPC`?
