### ISSUE TITLE
config.json "StatueSpawnXXX" Not working

### ISSUE THREAD

**Issue by axel37** [Pryaxis/TShock#1357] opened 2016-12-22 12:29 UTC
1.3.4.4 Pre-release 2

In the config.json, there are those lines 
`"StatueSpawn200": 3,
  "StatueSpawn600": 6,
  "StatueSpawnWorld": 10,`

> How many things a statue can spawn within XXX pixels(?) before it stops spawning.

I tried modifying these to : 200, 300 and 500, but in-game, nothing changed (they are still at default values)

**Comment by WhiteXZ** [comment] 2016-12-28 23:49
Possibly requires a modification to work again
Or it's not been working for a while - could you test if these options work in a non-mintaka version?

**Comment by axel37** [comment] 2016-12-29 16:22
> could you test if these options work in a non-mintaka version?
Because there are non-mintaka version for 1.3.4.4 ?
I didn't see any...

**Comment by AsterPiano** [comment] 2017-01-12 13:30
I tried downgrading my Terraria in order to test it with Tshock 4.3.20 but when I attempt to launch the server I immediately get an error and it closes :disappointed: http://pastebin.com/GncHiLD2

**Comment by WhiteXZ** [comment] 2017-01-12 13:33
You'll probably need to use an old world file (or one generated by the old server), @AsterPiano

**Comment by AsterPiano** [comment] 2017-01-12 13:42
Hmm, but this happens before I can choose a world, and looks like it might a problem with it actually getting the world list and listing the worlds. I tried backing up and removing all my worlds other than a couple of old ones but still the same thing happens.

**Comment by OnsenManju** [comment] 2017-01-14 22:42
@axel37, @WhiteXZ:
I could reproduce it by using the world like this.
![spawntest](https://cloud.githubusercontent.com/assets/16373401/21958521/b1fd9f36-daf3-11e6-821f-83264730250c.png)
file: [SpawnTest.wld](https://app.box.com/s/34yq9pgm4dfmeamf6mwccsew3g15duma)

With these configurations (twice as many as the default),
```
  "StatueSpawn200": 6,
  "StatueSpawn600": 12,
  "StatueSpawnWorld": 20,
```
20 skeletons were spawned correctly on Terraria 1.3.3.3 with TShock 4.3.20.
[capture (02:05)](https://my.mixtape.moe/mwdcvn.mp4)
(Please focus the skeleton statue and see how it spawns and stops)

But on Terraria 1.3.4.4 with TShock 4.3.22, amount of skeletons didn't exceed the default value.
[capture (01:30)](https://my.mixtape.moe/dpkady.mp4)

**Comment by WhiteXZ** [comment] 2017-01-14 22:47
Thanks mate, I'll have a look and see what's going on when I'm next able :)

**Comment by WhiteXZ** [comment] 2017-05-14 12:52
@DeathCradle this is likely something that will need a modification. Any input?

**Comment by DeathCradle** [comment] 2017-05-15 12:40
@WhiteXZ certainly does require a fixerino.
![image](https://cloud.githubusercontent.com/assets/776327/26057979/2b47f916-39bf-11e7-89ee-0d45dde6a05c.png)

**Comment by DeathCradle** [comment] 2017-05-15 13:55
Please give this build of TSAPI a whirl: https://ci.appveyor.com/project/hakusaro/terrariaapi-server/build/66/artifacts

**Comment by ProfessorXZ** [comment] 2017-07-06 11:16
@axel37 please test this with the latest release. @OnsenManju would like to ask you to test this too if you have time.

**Comment by axel37** [comment] 2017-07-08 10:13
Well...
![capture 2017-07-08 12_10_46](https://user-images.githubusercontent.com/11683059/27984468-d49e4448-63d6-11e7-9f6d-a3441e5840ca.png)

**Comment by ProfessorXZ** [comment] 2017-07-08 12:31
@axel37 I'll be honest and say that I have no idea what that screenshot is trying to show.

**Comment by tlworks** [comment] 2017-07-08 13:21
It shows that there's no limit. Because when the StatueSpawnXXX Quota is met, that specific statue will no longer spawn npc's.

**Comment by axel37** [comment] 2017-07-08 23:22
@ProfessorXZ 
There are a bunch of bunnies
That means that

> There are a bunch of bunnies

the _StatueSpawnXXX_ setting now works

**Comment by Ijwu** [comment] 2017-07-08 23:40
Unless I've misunderstood, that sounds like this is fixed and no longer relevant. Closing issue.

Re-open if I'm wrong.

**Closed by Ijwu** 2017-07-08 23:40 UTC
